function [fitresult, gof] = createFit(d, m0)
%CREATEFIT(D,M0)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: d
%      Y Output: m0
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Jan-2024 20:20:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( d, m0 );

% Set up fittype and options.
ft = fittype( 'a*x^(-b)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.616044676146639 0.473288848902729 0.351659507062997];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'm0 vs. d', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'd', 'Interpreter', 'none' );
ylabel( 'm0', 'Interpreter', 'none' );
grid on


