from labscript import *

# from labscript_devices.PulseBlasterUSB import PulseBlasterUSB
from labscript_devices.Pyncmaster import Pyncmaster as PulseBlasterUSB

PulseBlasterUSB(name='pulseblaster_0', board_number=0, time_based_stop_workaround=True, time_based_stop_workaround_extra_time=0,clock_rate=30)

DigitalOut(name='channel_1',parent_device=pulseblaster_0.direct_outputs,connection='flag 0')
DigitalOut(name='channel_2',parent_device=pulseblaster_0.direct_outputs,connection='flag 1')
DigitalOut(name='channel_3',parent_device=pulseblaster_0.direct_outputs,connection='flag 2')
DigitalOut(name='channel_4',parent_device=pulseblaster_0.direct_outputs,connection='flag 3')
DigitalOut(name='channel_5',parent_device=pulseblaster_0.direct_outputs,connection='flag 4')
DigitalOut(name='channel_6',parent_device=pulseblaster_0.direct_outputs,connection='flag 5')
DigitalOut(name='channel_7',parent_device=pulseblaster_0.direct_outputs,connection='flag 6')
DigitalOut(name='channel_8',parent_device=pulseblaster_0.direct_outputs,connection='flag 7')
DigitalOut(name='channel_9',parent_device=pulseblaster_0.direct_outputs,connection='flag 8')
DigitalOut(name='channel_10',parent_device=pulseblaster_0.direct_outputs,connection='flag 9')
DigitalOut(name='channel_11',parent_device=pulseblaster_0.direct_outputs,connection='flag 10')
DigitalOut(name='channel_12',parent_device=pulseblaster_0.direct_outputs,connection='flag 11')
DigitalOut(name='channel_13',parent_device=pulseblaster_0.direct_outputs,connection='flag 12')
DigitalOut(name='channel_14',parent_device=pulseblaster_0.direct_outputs,connection='flag 13')
DigitalOut(name='channel_15',parent_device=pulseblaster_0.direct_outputs,connection='flag 14')
DigitalOut(name='channel_16',parent_device=pulseblaster_0.direct_outputs,connection='flag 15')
DigitalOut(name='channel_17',parent_device=pulseblaster_0.direct_outputs,connection='flag 16')
DigitalOut(name='channel_18',parent_device=pulseblaster_0.direct_outputs,connection='flag 17')
DigitalOut(name='channel_19',parent_device=pulseblaster_0.direct_outputs,connection='flag 18')
DigitalOut(name='channel_20',parent_device=pulseblaster_0.direct_outputs,connection='flag 19')
DigitalOut(name='channel_21',parent_device=pulseblaster_0.direct_outputs,connection='flag 20')
DigitalOut(name='channel_22',parent_device=pulseblaster_0.direct_outputs,connection='flag 21')
DigitalOut(name='channel_23',parent_device=pulseblaster_0.direct_outputs,connection='flag 22')
DigitalOut(name='channel_24',parent_device=pulseblaster_0.direct_outputs,connection='flag 23')
DigitalOut(name='channel_25',parent_device=pulseblaster_0.direct_outputs,connection='flag 24')
DigitalOut(name='channel_26',parent_device=pulseblaster_0.direct_outputs,connection='flag 25')
DigitalOut(name='channel_27',parent_device=pulseblaster_0.direct_outputs,connection='flag 26')
DigitalOut(name='channel_28',parent_device=pulseblaster_0.direct_outputs,connection='flag 27')
DigitalOut(name='channel_29',parent_device=pulseblaster_0.direct_outputs,connection='flag 28')
DigitalOut(name='channel_30',parent_device=pulseblaster_0.direct_outputs,connection='flag 29')
DigitalOut(name='channel_31',parent_device=pulseblaster_0.direct_outputs,connection='flag 30')
DigitalOut(name='channel_32',parent_device=pulseblaster_0.direct_outputs,connection='flag 31')
DigitalOut(name='channel_33',parent_device=pulseblaster_0.direct_outputs,connection='flag 32')
DigitalOut(name='channel_34',parent_device=pulseblaster_0.direct_outputs,connection='flag 33')
DigitalOut(name='channel_35',parent_device=pulseblaster_0.direct_outputs,connection='flag 34')
DigitalOut(name='channel_36',parent_device=pulseblaster_0.direct_outputs,connection='flag 35')
DigitalOut(name='channel_37',parent_device=pulseblaster_0.direct_outputs,connection='flag 36')
DigitalOut(name='channel_38',parent_device=pulseblaster_0.direct_outputs,connection='flag 37')
DigitalOut(name='channel_39',parent_device=pulseblaster_0.direct_outputs,connection='flag 38')
DigitalOut(name='channel_40',parent_device=pulseblaster_0.direct_outputs,connection='flag 39')
DigitalOut(name='channel_41',parent_device=pulseblaster_0.direct_outputs,connection='flag 40')
DigitalOut(name='channel_42',parent_device=pulseblaster_0.direct_outputs,connection='flag 41')
DigitalOut(name='channel_43',parent_device=pulseblaster_0.direct_outputs,connection='flag 42')
DigitalOut(name='channel_44',parent_device=pulseblaster_0.direct_outputs,connection='flag 43')
DigitalOut(name='channel_45',parent_device=pulseblaster_0.direct_outputs,connection='flag 44')
DigitalOut(name='channel_46',parent_device=pulseblaster_0.direct_outputs,connection='flag 45')
DigitalOut(name='channel_47',parent_device=pulseblaster_0.direct_outputs,connection='flag 46')
DigitalOut(name='channel_48',parent_device=pulseblaster_0.direct_outputs,connection='flag 47')
DigitalOut(name='channel_49',parent_device=pulseblaster_0.direct_outputs,connection='flag 48')
DigitalOut(name='channel_50',parent_device=pulseblaster_0.direct_outputs,connection='flag 49')
DigitalOut(name='channel_51',parent_device=pulseblaster_0.direct_outputs,connection='flag 50')
DigitalOut(name='channel_52',parent_device=pulseblaster_0.direct_outputs,connection='flag 51')
DigitalOut(name='channel_53',parent_device=pulseblaster_0.direct_outputs,connection='flag 52')
DigitalOut(name='channel_54',parent_device=pulseblaster_0.direct_outputs,connection='flag 53')
DigitalOut(name='channel_55',parent_device=pulseblaster_0.direct_outputs,connection='flag 54')
DigitalOut(name='channel_56',parent_device=pulseblaster_0.direct_outputs,connection='flag 55')
DigitalOut(name='channel_57',parent_device=pulseblaster_0.direct_outputs,connection='flag 56')
DigitalOut(name='channel_58',parent_device=pulseblaster_0.direct_outputs,connection='flag 57')
DigitalOut(name='channel_59',parent_device=pulseblaster_0.direct_outputs,connection='flag 58')
DigitalOut(name='channel_60',parent_device=pulseblaster_0.direct_outputs,connection='flag 59')
DigitalOut(name='channel_61',parent_device=pulseblaster_0.direct_outputs,connection='flag 60')
DigitalOut(name='channel_62',parent_device=pulseblaster_0.direct_outputs,connection='flag 61')
DigitalOut(name='channel_63',parent_device=pulseblaster_0.direct_outputs,connection='flag 62')
DigitalOut(name='channel_64',parent_device=pulseblaster_0.direct_outputs,connection='flag 63')

if __name__ == '__main__':
    start()
    stop(1)
